### ISSUE TITLE
refactor: improve static wrapper

### ISSUE THREAD

**Issue by 0xClandestine** [oguimbal/HyVM#46]
I think the flow would be a bit more consistent if `staticExec` was actually just a fallback.

```js
staticHyvm.staticcall("")
```

vs

```js
staticHyvm.staticExec("")
```

There's an example [here.](https://github.com/0xClandestine/crystal-ball/blob/main/src/CrystalBallStatic.sol) 🫡

**Comment by obatirou** [comment]
Hi @0xClandestine 
Sorry for the delay, thank you for the suggestion.
This was audited  like this before this issue so I do not think we will make a change.
